#define IL_ASSIGN            1
#define IL_ASDIV             3
#define IL_ASMUL             5
#define IL_ASMOD             7
#define IL_ASADD             9
#define IL_ASSUB            11
#define IL_ASSHL            13
#define IL_ASSHR            15
#define IL_ASAND            17
#define IL_ASOR             19
#define IL_ASXOR            21
#define IL_EQU              23
#define IL_NEQU             25
#define IL_GT               27
#define IL_GTE              29
#define IL_LTE              31
#define IL_LT               33
#define IL_SHR              35
#define IL_SHL              37
#define IL_BITOR            39
#define IL_BITAND           41
#define IL_BITXOR           43
#define IL_DIV              45
#define IL_MOD              47
#define IL_PREINC           49
#define IL_PREDEC           51
#define IL_POSTINC          53
#define IL_POSTDEC          55
#define IL_BITNOT           57
#define IL_NOT              59
#define IL_WIDX             61
#define IL_BIDX             63
#define IL_COMMA            65
#define IL_QUERY            67
#define IL_COLON            69
#define IL_LOGOR            71
#define IL_LOGAND           73
#define IL_ADD              75
#define IL_SUB              77
#define IL_MUL              79
#define IL_LVAL             81
#define IL_RVAL             83
#define IL_ASBYTE           85
#define IL_BFETCH           87
#define IL_WFETCH           89
#define IL_NFCTN_CALL       91
#define IL_FCTN_CALL        93
#define IL_MARK             95
#define IL_RQD              97
#define IL_RASGN            99
#define IL_RASDIV          101
#define IL_RASMUL          103
#define IL_RASMOD          105
#define IL_RASADD          107
#define IL_RASSUB          109
#define IL_RASSHL          111
#define IL_RASSHR          113
#define IL_RASAND          115
#define IL_RASOR           117
#define IL_RASXOR          119
#define IL_RSHR            121
#define IL_RSHL            123
#define IL_RSUB            125
#define IL_RASBYTE         127
#define IL_RDIV            129
#define IL_RMOD            131
#define IL_RBIDX           133
#define IL_NULL            135
#define IL_BITANDN         137
#define IL_ADDR            139
#define IL_NEG             141
#define IL_LAST            141
