  TITL 'SELECT OPCODE AND JUMP - CORTEX BASIC REV. 1.1'
        IDT  'JMP'
*
* ROUTINE LIST:
*       JMPR0A      PICK UP NEXT BYTE FROM PROGRAM, STORE
*                   IT IN THE DLC AND JUMP ON ITS CONTENTS
*       JMPR0       JUMP ON CONTENTS OF R0
*
* MODULE DEFINITIONS:
*
        DEF  JMPR0A,JMPR0
*
* EXTERNAL ROUTINES:
*
*
* EXTERNAL DATA:
*
        REF DLIM
*
* ABSTRACT:
*
* JMPR0A IS SIMPLY A ROUTINE TO SAVE MEMORY WHEN
* DECIDING UPON AN ACTION FROM A TABLE OF ALTERNATIVES
* SELECTED BY A BYTE CODE.
*
* CALLING SEQUENCE:
*
*          BL   @JMPR0   OR BL   @JMPR0A
* TABLE    BYTE DISP,BYTE
*          BYTE DISP,BYTE
*          ...
*          DATA 0
*
*       IN R8 = PBC
*       OUT DLIM UPDATED (IF JMPR0A)
*
* EXIT TO TABLE+DISP ON BYTE FOUND
*       OTHERWISE INSTRUCTION IMMEDIATELY AFTER TABLE
*
        PAGE
*
* ENTRY POINT FOR JMPR0A
*
JMPR0A  CLR  R0
        MOVB *R8+,R0      GET NEXT BYTE FROM PROGRAM
        MOV  R0,@DLIM     SAVE AND DROP THRU INTO JMPR0
*
* ENTRY POINT FOR JMPR0
*
JMPR0   MOV  R11,R2       GET TABLE ADR
*
* NEXT INSTRUCTION INSERTED TO OVERCOME PROBLEM WITH
* ODD ADDRESS GENERATION (WITH TMS9980 AND 81 PROCESSORS)
*
        CLR  R1
*
JMPR01  MOVB *R11+,R1     GET DISPLACEMENT, DONE?
        JEQ  JMPR02       Y - INSTRUCTION FOLLOWING TABLE
        CB   R0,*R11+     N - CODE FOUND?
        JNE  JMPR01       N - KEEP LOOKING
        SRA  R1,7         Y - POSITION
        A    R1,R2        ADD DISPLACEMENT
        B    *R2          GOTO ROUTINE
*
* BYTE OPCODE NOT FOUND - RETURN TO INSTRUCTION
* IMMEDIATELY FOLLWOING THE TABLE
*
JMPR02  INC  R11          MOVE TO NEXT LINE
        RT
        END
        