all:  	rom.bin


start.obj: start.asm
	asm990 -a "BUNLST,TUNLST,DUNLST,MUNLST" -l start.lst -o start.obj start.asm

mid.obj: mid.asm
	asm990 -a "BUNLST,TUNLST,DUNLST,MUNLST" -l mid.lst -o mid.obj mid.asm

dsr02.obj: dsr02.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l dsr02.lst -o dsr02.obj dsr02.asm

centron.obj: centron.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l centron.lst -o centron.obj centron.asm

vdpdsr.obj: vdpdsr.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l vdpdsr.lst -o vdpdsr.obj vdpdsr.asm

monitor.obj: monitor.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l monitor.lst -o monitor.obj monitor.asm

jump.obj: jump.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l jump.lst -o jump.obj jump.asm

cassette.obj: cassette.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l cassette.lst -o cassette.obj cassette.asm

centron.obj: centron.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l centron.lst -o centron.obj centron.asm

atnf.obj: atnf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l atnf.lst -o atnf.obj atnf.asm

vdp.obj: vdp.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l vdp.lst -o vdp.obj vdp.asm

error.obj: error.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l error.lst -o error.obj error.asm

call.obj: call.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l call.lst -o call.obj call.asm

chrf.obj: chrf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l chrf.lst -o chrf.obj chrf.asm

cruf.obj: cruf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l cruf.lst -o cruf.obj cruf.asm

def.obj: def.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l  def.lst -o  def.obj  def.asm

dim.obj: dim.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l dim.lst -o dim.obj dim.asm

enter.obj: enter.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l enter.lst -o enter.obj enter.asm

escape.obj: escape.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l escape.lst -o escape.obj escape.asm

for.obj: for.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l for.lst -o for.obj for.asm

format.obj: format.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l format.lst -o format.obj format.asm

func.obj: func.asm
	asm990 -a "BUNLST,TUNLST,DUNLST,MUNLST" -l func.lst -o func.obj func.asm

gosub.obj: gosub.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l gosub.lst -o gosub.obj gosub.asm

if.obj: if.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l if.lst -o if.obj if.asm

input.obj: input.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l input.lst -o input.obj input.asm

ipcom.obj: ipcom.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l ipcom.lst -o ipcom.obj ipcom.asm

let.obj: let.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l let.lst -o let.obj let.asm

logops.obj: logops.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l logops.lst -o logops.obj logops.asm

memf.obj: memf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l memf.lst -o memf.obj memf.asm

move.obj: move.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l move.lst -o move.obj move.asm

mwdf.obj: mwdf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l mwdf.lst -o mwdf.obj mwdf.asm

number.obj: number.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l  number.lst -o  number.obj  number.asm

on.obj: on.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l on.lst -o on.obj on.asm

print.obj: print.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l print.lst -o print.obj print.asm

purge.obj: purge.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l purge.lst -o purge.obj purge.asm

putb.obj: putb.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l putb.lst -o putb.obj putb.asm

random.obj: random.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l random.lst -o random.obj random.asm

read.obj: read.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l read.lst -o read.obj read.asm

renum.obj: renum.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l renum.lst -o renum.obj renum.asm

sgnf.obj: sgnf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l sgnf.lst -o sgnf.obj sgnf.asm

size.obj: size.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l size.lst -o size.obj size.asm

ticf.obj: ticf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l ticf.lst -o ticf.obj ticf.asm

time.obj: time.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l  time.lst -o  time.obj  time.asm

trace.obj: trace.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l trace.lst -o trace.obj trace.asm

unit.obj: unit.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l unit.lst -o unit.obj unit.asm

boot.obj: boot.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l boot.lst -o boot.obj boot.asm

sfsn.obj: sfsn.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l sfsn.lst -o sfsn.obj sfsn.asm

swap.obj: swap.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l swap.lst -o swap.obj swap.asm

relops.obj: relops.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l relops.lst -o relops.obj relops.asm

edit.obj: edit.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l edit.lst -o edit.obj edit.asm

run.obj: run.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l run.lst -o run.obj run.asm

cvbd.obj: cvbd.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l cvbd.lst -o cvbd.obj cvbd.asm

cvdb.obj: cvdb.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l cvdb.lst -o cvdb.obj cvdb.asm

cvgc.obj: cvgc.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l cvgc.lst -o cvgc.obj cvgc.asm

eval.obj: eval.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l eval.lst -o eval.obj eval.asm

expf.obj: expf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l expf.lst -o expf.obj expf.asm

fix.obj: fix.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l  fix.lst -o  fix.obj  fix.asm

fp.obj: trace.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l fp.lst -o fp.obj fp.asm

bitf.obj: unit.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l bitf.lst -o bitf.obj bitf.asm

getline.obj: boot.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l getline.lst -o getline.obj getline.asm

getp2.obj: getp2.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l getp2.lst -o getp2.obj getp2.asm

getparm.obj: getparm.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l getparm.lst -o getparm.obj getparm.asm

logf.obj: logf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l logf.lst -o logf.obj logf.asm

plot.obj: plot.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l plot.lst -o plot.obj plot.asm

poly.obj: poly.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l poly.lst -o poly.obj poly.asm

powf.obj: powf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l powf.lst -o powf.obj powf.asm

rndf.obj: rndf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l rndf.lst -o rndf.obj rndf.asm

sinf.obj: sinf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l sinf.lst -o sinf.obj sinf.asm

sqrf.obj: sqrf.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l sqrf.lst -o sqrf.obj sqrf.asm

extend.obj: extend.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l extend.lst -o extend.obj extend.asm

text.obj: text.asm
	asm990 -a "BUNLST,TUNLST,DUNLST,MUNLST" -l text.lst -o text.obj text.asm

last.obj: last.asm
	asm990 -a "BUNLST,DUNLST,MUNLST" -l last.lst -o last.obj last.asm


rom.bin: start.obj mid.obj dsr02.obj centron.obj vdpdsr.obj monitor.obj jump.obj cassette.obj atnf.obj \
         vdp.obj error.obj call.obj chrf.obj cruf.obj def.obj dim.obj enter.obj escape.obj for.obj format.obj func.obj gosub.obj \
        if.obj input.obj ipcom.obj let.obj logops.obj memf.obj move.obj mwdf.obj number.obj on.obj print.obj purge.obj putb.obj random.obj \
	read.obj renum.obj sgnf.obj size.obj ticf.obj time.obj trace.obj unit.obj boot.obj sfsn.obj swap.obj relops.obj edit.obj run.obj \
	cvbd.obj cvdb.obj cvgc.obj eval.obj expf.obj fix.obj fp.obj bitf.obj getline.obj getp2.obj getparm.obj \
	logf.obj plot.obj poly.obj powf.obj rndf.obj sinf.obj sqrf.obj extend.obj text.obj last.obj
	lnk990 -a -m rom.map -o rom.bin start.obj mid.obj dsr02.obj centron.obj vdpdsr.obj monitor.obj jump.obj cassette.obj atnf.obj \
	vdp.obj error.obj call.obj chrf.obj cruf.obj def.obj dim.obj enter.obj escape.obj for.obj format.obj func.obj gosub.obj \
        if.obj input.obj ipcom.obj let.obj logops.obj memf.obj move.obj mwdf.obj number.obj on.obj print.obj purge.obj putb.obj random.obj \
	read.obj renum.obj sgnf.obj size.obj ticf.obj time.obj trace.obj unit.obj boot.obj sfsn.obj swap.obj relops.obj edit.obj run.obj \
	cvbd.obj cvdb.obj cvgc.obj eval.obj expf.obj fix.obj fp.obj bitf.obj getline.obj getp2.obj getparm.obj \
	logf.obj plot.obj poly.obj powf.obj rndf.obj sinf.obj sqrf.obj extend.obj text.obj last.obj



pretty:
	cp *.asm ./backup
#	pretty6502 -p4 -a0 -du -mu -c50 -l ./backup/start.asm start.asm

clean:
	@rm -f *.obj
	@rm -f *.map
	@rm -f *.lst
	@rm -f *.bin
	@rm -f *.bak
