        TITL 'MWD & ADR ROUTINES - CORTEX BASIC REV. 1.1'
        IDT  'MWDF'
        DEF  MWDY,MWDF,ADRF
*
*       MWDY             MWD COMMAND
*       MWDF             MWD FUNCTION
*       ADRF             ADR FUNCTION
*
        REF EVERZ       ;EVALUATE EXPRESSION
        REF PFIX        ;FIX 16 BIT NUMBER
        REF GPRM2       ;GET PARAMETERS
        REF NLIN        ;EXIT ENTRY TO MULTIPLEXOR
        REF EVSFR$      ;EXIT ENTRY TO EVALUATOR, LOAD R2 WITH FPAC
        REF FPAC,FPAC2  ;FLOATING POINT ACCUMULATOR
        REF B4A         ;>4A
*
        DXOP STORE,1    ;STORE FPAC
        DXOP CLEAR,8    ;CLEAR FPAC
        DXOP EVFIX,11   ;EVALUATE AND FIX
        DXOP OUTFP,12   ;OUT FLOATING POINT #
ERROR   EQU >2F80       ;XOP XX,14  (ERROR CALL)
       PAGE
*       THE MWD COMMAND ALLOWS PBASIC TO ALTER
*       A WORD OF MEMORY WHILE THE MEM FUNCTION
*       ALLOWS PBASIC TO READ A WORD OF
*       MEMORY.
*
* CALLING SEQUENCE:
*
*       B @MWDY
*       EXIT TO NLIN
*
*       B @MWDF
*       IN  (R2) = ADDRESS
*       OUT (R2) = RESULT
*       EXIT TO EVSFR$
*
* EXCEPTIONS AND CONDITIONS:
*
*       EVALUATION ERRORS
*       SYNTAX ERROR
*
MWDY    CB *R8+,@B4A    ;LEFT BRACKET?
          JNE ERR1      ;N, ERROR
        BLWP @EVERZ     ;GET ADDRESS
        BL @PFIX        ;GET INTEGER
        BL @GPRM2       ;CHECK PARAMETERS
        MOV  R3,*R1     ;STORE BYTE IN MEMORY
        B @NLIN
*
ERR1    DATA ERROR+1
*
* READ MEMORY
*
MWDF    BL @PFIX         ;GET PARAMETER
        MOV  *R1,R1      ;GET BYTE
        CLEAR 0          ;CLEAR FPAC
MWDF1   MOV R1,@FPAC2    ;SAVE
       B    @EVSFR$      ;RELOAD R2 & EXIT TO EVAL
*
* ADR - RETURN THE ADDRESS OF THE SPECIFIED VARIABLE/ARRAY
*       ELEMENT.  APPEARS IN THIS MODULE TO SAVE MEMORY.
*
ADRF    MOV  R2,R1    ARGUMENT'S ADDRESS IN R2
        JMP  MWDF1
        END
