CC=cc
YACC=yacc
LEX=lex

CFLAGS=-O -I.
YFLAGS=-d

all:	awk

FILES=awk.lx.o b.o main.o token.o tran.o lib.o run.o parse.o proctab.o 

awk:	$(FILES) awk.g.o
	${CC} $(CFLAGS) -o awk awk.g.o $(FILES) 

clean:
	rm -f ${FILES} awk awk.g.o
	rm -f proc proc.o

y.tab.h:	awk.g.o

awk.h:	y.tab.h
	cp y.tab.h awk.h

$(FILES):	awk.h awk.def

token.c:	awk.h
	ed - <tokenscript
	rm temp

awk.g.c: awk.g.y
	${YACC} -d awk.g.y
	mv -f y.tab.c awk.g.c

awk.g.o: awk.g.c
	${CC} -I. -c awk.g.c
