       TITL 'CALL HANDLER - CORTEX BASIC REV. 1.1'
       IDT  'CALL'
*      
*      CALL HANDLER
*
       DEF  CLLY
       REF  EVSDZ
       REF  NLIN
       REF  CALLWP,CALL12
ERROR  EQU  >2F80
       DXOP EVFIX,11
*
* CALL COMMAND
*
*   CALL "ROUTINE",ADDRESS,PARMS.....,PARMS
*
* THE ROUTINE NAME FIELD IS OPTIONAL
* PARMS (UPTO 12) ARE SEPARATED BY COMMAS
* THESE ARE STORED IN THE USER'S REGISTERS R0 - R11;
* R12 CONTAINS THE NUMBER OF ARGUMENTS PASSED OVER.
*
* PARMS SHOULD BE EITHER:
*      INTEGER VALUES/EXPRESSIONS   OR
*      THE ADDRESS OF THE VARIABLE/ARRAY ELEMENT
*      CONTAINING THE DESIRED PARAMETER.
*
* THE ADDRESS OF X IS PASSED BY  -  ADR(X)
       PAGE
*
* SET UP THE BLWP VECTOR IN R4,R5 FOR THE USER'S PROG
*
CLLY   LI   R12,CALLWP        REF "USER'S" WORKSPACE
       LI   R11,CALL12        REF LAST+1 USEABLE REGISTER
       BLWP @EVSDZ            ALLOW STRING CONSTANT
       JMP  GETPC             OK, STRING CONSTANT  ("---")
       DATA ERROR+1           WRONG, STRING VARIABLE  ($VAR)
*                             NEITHER, DROP THROUGH TO GETPC
GETPC  CLR  R2                RESET COUNT
       MOV  R12,R4            SET CALLVEC'S WP
       EVFIX R5               GET PC
CLL2   CI   R0,>3F00          PARAMETERS?
       JNE  CLL4              N, EXIT TO USER ROUTINE
       INC  R2                Y, INCREMENT COUNT
CLL2A  EVFIX *R12+            STUFF NEXT ARGUMENT INTO REGISTER
       C    R12,R11           REGISTER'S FULL?
       JL   CLL2              N - BACK FOR NEXT ARGUMENT
*
* ALL ARGUMENTS HAVE BEEN STORED IN THE REGISTERS
* (OR ALL THAT ARE GOING TO BE HANDLED)
*
CLL4   MOV  R2,*R11           SAVE COUNT IN USER'S R12
       BLWP R4                BLWP TO USER'S ROUTINE
       B    @NLIN             RETURNS TO HERE
       END
