       TITL 'RANDOM FUNCTION - CORTEX BASIC REV. 1.1'
       IDT  'RNDF'
*
*       RANDG           ;RANDOM NUMBER GENERATOR
*       RAND            ;GET FLOATING POINT RANDOM NUMBER
*
        REF FNRM              ;FIXES ARGUMENT
        REF RANDS               ;RANDOM SEED
        REF FPWP                ;FLOATING POINT WORKSPACE POINTER
*
*       RETURNS A 16 BIT RANDOM NUMBER.  THE SEED
*       IS MAINTAINED IN RANDS AND IS UPDATED
*       ON EACH CALL.
*
* GENERATE PSEUDO RANDOM SEQUENCE OF INTEGERS
*
*       LINEAR CONGRUENTIAL SEQUENCE:
*       X[N+1] = (X[N] * A + C) MOD 2^16
*
* USE MOST SIGNIFICANT K-BITS IF <16 ARE REQUIRED
       PAGE
* CALLING SEQUENCE:
*
*       BL @RANDG
*
*       OUT R0 = 16 BIT RANDOM NUMBER
*
*
RANDG   MOV @RANDS,R0   ;GET RANDOM SEED
        MOV R0,R3
        SLA R3,11       ;N*2^11
        A R0,R3         ;N*2^11+N
        SLA R3,2
        A R3,R0         ;N*2^11+5N
        AI R0,13849     ;(N*A+13849.)  MOD 2^16
        MOV R0,@RANDS   ;STORE NEW SEED
        RT
*
*
* ABSTRACT:
*
*       RETURNS A FLOATING POINT RANDOM NUMBER IN FPAC.
*       TWO 16-BIT RANDOM NUMBERS ARE USED TO GENERATE
*       THE THREE WORD FLOATING POINT NUMBER.
*
* CALLING SEQUENCE:
*
*       BLWP @RANDZ
*
*       OUT FPAC = FLOATING POINT RANDOM NUMBER
*
*       FNRM            ;NORMALIZE NUMBER
        DEF RANDZ
*
RANDZ  DATA FPWP,RAND
*
RAND    BL @RANDG       ;GET RANDOM #
        MOV R0,R1
        BL @RANDG
        MOV R0,R2       ;LOAD LOW
        LI R0,>4200     ;ADD EXPONENT
        B @FNRM         ;NORMALIZE
        END
